[Feat]#109- 지도 페이지 UI작업
NBCAMP-ToDwoong/todwoong pull request #131
Opened 2024-03-14 08:55 UTC by Whited123

… 메인화면에서 셀의 장소버튼 클릭 시 지도페이지로 전환하는 추가 작업도 수행하였습니다. 그리고 위치권한에 따른 설정창 이동유도 로직도 작성하였습니다.

## 연관된 이슈

> #109 

## 작업 내용

> 지도페이지의 카테고리칩관련 UI를 일부 개선(클릭 시 버튼 하이라이트 문제, 스크롤뷰 isHidden기능, 레이아웃 관련) 하고, 투두리스트와의 중복코드(그룹칩UI관련)를 별도의 파일로 만들어서 작성했습니다.
> 지도페이지에 진입 시 위치 권한이 허용 안되어 있다면 alert창을 띄워서 사용자에게 설정창으로 유도하는 기능을 추가했습니다.
> 메인화면에서 셀의 장소버튼 클릭 시 지도페이지로 이동 후 해당 장소를 줌인해주는 기능을 추가했습니다.

## 리뷰 요구사항 (선택)

> 현재 메인화면에서 지도페이지로 이동하는 로직은 주석처리 되어있습니다. 코드 리뷰해보시고 추가할 부분이나 수정할 부분이 있다면 말씀해주세요.

## 스크린샷 (선택)

![Mar-14-2024 17-43-16](https://github.com/NBCAMP-ToDwoong/todwoong/assets/123481645/ead8e184-9f69-43f4-a67d-0490b053b34a)

2024-03-14 11:56 UTC, yenny42 requested changes
p1;
리스트 비어있을 때 보이는 둥이!! 뷰 추가해주세요ㅎㅎ

![스크린샷 2024-03-14 오후 8 53 10](https://github.com/NBCAMP-ToDwoong/todwoong/assets/107637741/f10b1918-64f8-4d2c-818a-438f54d6030b)

2024-03-14 11:59 UTC, yenny42 reviewed
p3;
모달 배경색 lightGray로 변경해주세요!

2024-03-15 00:35 UTC, codeIsGone approved these changes
고생하셨습니다.

2024-03-15 01:39 UTC, yenny42 commented
모달창 내부 중앙 정렬이 안 되어 있는 것 같습니다!

<img src="https://github.com/NBCAMP-ToDwoong/todwoong/assets/107637741/2af695b5-1c99-423b-87d2-1a60c16167cc" width="300" />

2024-03-15 05:19 UTC, yenny42 approved these changes
수고하셨습니다 🥸

2024-03-15 06:41 UTC, merged