[Feat]#12 - 투두 리스트 UI 구현
NBCAMP-ToDwoong/todwoong pull request #30
Opened 2024-03-04 08:32 UTC by codeIsGone

## 연관된 이슈

> #12

## 작업 내용

> 투두 리스트 페이지의 UI 및 관련 메서드 아웃라인을 구현했습니다.

## 리뷰 요구사항 (선택)

> 더 효율적으로 레이아웃 잡을 수 있는 방법이 있다면 추천해주세요!

## 스크린샷 (선택)

|기본|스와이프->|스와이프<-|
|---|---|---|
|<img src="https://github.com/NBCAMP-ToDwoong/todwoong/assets/151711359/d4462c6a-4e89-40dd-ab9c-aa4671501917" width="300"/>|<img src="https://github.com/NBCAMP-ToDwoong/todwoong/assets/151711359/4787244a-8b7f-47fc-a97d-f1ed0fa73bd8" width="300"/>|<img src="https://github.com/NBCAMP-ToDwoong/todwoong/assets/151711359/da980134-23cc-4553-b3e7-efb4309ee593" width="300"/>|

2024-03-04 10:57 UTC, yenny42 requested changes

2024-03-04 10:57 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/TodoList/View/TodoView.swift
> +        ].forEach{self.addSubview($0)}
띄어쓰기 해 주세요~ 😁

2024-03-04 10:57 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoViewController.swift
> +class TodoViewController: UIViewController {
p2;
데이터가 없을 때 화면이 너무 비어보이는 것 같아요
제가 피그마에 간단히 디자인을 추가해보았는데 이걸 넣어보면 어떨까요?
더 좋은 의견 언제나 환영입니다ㅎㅎ

2024-03-04 10:57 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoViewController.swift
> +    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
p5;
셀 선택시 배경이 회색으로 고정되는 (기본 cell 디자인) 부분은
다음 피쳐에서 수정 예정이실까요~?
색상을 없애거나 애니메이션 처리를 해야 할 거 같은데 이 부분은 다같이 통일하면 좋겠네요
@mirae0312 @Whited123 @codeIsGone

2024-03-04 10:58 UTC, yenny42 commented
+) 스위프트 린트 노란색으로 주의 뜨는 것 수정 부탁드립니다!

2024-03-04 10:59 UTC, yenny42 commented
PR에 Label 달아주세요 :)

2024-03-04 11:22 UTC, codeIsGone commented on ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoViewController.swift
> +    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
합의 완료

2024-03-04 11:36 UTC, Whited123 commented
확인했습니다!

2024-03-04 11:36 UTC, mirae0312 approved these changes
확인했습니다 👏

2024-03-05 01:03 UTC, codeIsGone commented on ToDwoong/ToDwoong/Presentation/TodoList/View/GroupCollectionViewCell.swift
> +    }()
814bf7aea1accbc1867d0b359efe40ec326757e8
적용했습니다!

2024-03-05 01:04 UTC, codeIsGone commented on ToDwoong/ToDwoong/Presentation/TodoList/View/GroupCollectionViewCell.swift
> +        groupButton.snp.makeConstraints {make in
814bf7aea1accbc1867d0b359efe40ec326757e8
넵

2024-03-05 01:04 UTC, codeIsGone commented on ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoViewController.swift
> +class TodoViewController: UIViewController {
814bf7aea1accbc1867d0b359efe40ec326757e8
좋아요~

2024-03-05 01:12 UTC, yenny42 approved these changes
수고하셨습니다 😌

2024-03-05 01:25 UTC, merged