[Feat]#11 - 카테고리 페이지 UI구현
NBCAMP-ToDwoong/todwoong pull request #32
Opened 2024-03-04 10:48 UTC by Whited123

## 연관된 이슈

> #11 

## 작업 내용

> 상단 네비게이션바에 버튼과 타이틀을 추가하고, 색상을 지정하였습니다.
> 그룹 추가 버튼을 추가 하였습니다.
> 테이블뷰를 추가하였습니다
> 네비게이션바의 편집버튼을 누르면 셀이 편집 상태(<->일반 상태)로 전환되게 만들었습니다.
> 노말 상태에서 셀을 좌로 스와이프하면 수정 및 삭제가 가능하게 만들었습니다.
> 편집 상태에서 셀을 이동 시킬 수 있게 만들고 삭제가 가능하도록 만들었습니다.

## 리뷰 요구사항 (선택)

> 현재 셀의 모서리부분이 디자인이 덜 되었고, 코어데이터 연결이 안되어있습니다.
> 그룹 추가 버튼이나 뒤로가기 버튼, 해당 카테고리 수정 버튼의 로직이 작성되어 있지 않습니다.
> 메서드의 이름이나 코드에서 수정 해야할 부분이 있다면 말씀해주세요.

## 스크린샷 (선택)

![Mar-04-2024 19-42-23](https://github.com/NBCAMP-ToDwoong/todwoong/assets/123481645/a04f7a41-628b-43ed-ad42-c65c6110a772)

2024-03-04 11:08 UTC, yenny42 commented
이 내용을 각각 하나의 커밋으로 쪼개서 올려주시면 더 좋을 것 같아요 :) 
[읽어보시면 좋을 것 같은 블로그 글 가져왔어요](https://dj-min43.medium.com/git-%ED%94%84%EB%A1%9C%EB%8B%B5%EA%B2%8C-commit%ED%95%98%EB%8A%94-%EB%B2%95-2d0fc890f59a)

![스크린샷 2024-03-04 오후 8 00 44](https://github.com/NBCAMP-ToDwoong/todwoong/assets/107637741/8212a498-b2c3-4401-b683-194723d519b1)

2024-03-04 11:26 UTC, yenny42 requested changes

2024-03-04 11:26 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
> +
p1;
팀 코드 컨벤션에 따라 mark 주석 달아주세요

2024-03-04 11:26 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
> +}
p1;
extension은 따로 폴더 분리하여 작성해주세요!
하단 캡쳐 참조하여 폴더와 파일 생성하여 분리해주세요
![스크린샷 2024-03-04 오후 8 12 13](https://github.com/NBCAMP-ToDwoong/todwoong/assets/107637741/b4295f70-0534-453a-bcd4-076f501b7e03)

2024-03-04 11:26 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +final class GroupListView: UIView {
p1;
팀 코드 컨벤션에 따라 mark 주석 달아주세요

2024-03-04 11:26 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/TodoList/ViewController.swift
>  class ViewController: UIViewController {
p1;
본인이 작업하지 않는 파일은 수정하지 말아주세요!

2024-03-04 11:26 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +        // 스와이프 편집 버튼 누르면 호출되는 메서드
p3;
추후 작업할 부분이라면 FiXME 주석으로 작성해주세요

2024-03-04 11:26 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +}
q;
확장을 2개로 나누신 이유가 있을까요?

2024-03-04 11:26 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/ContentSizedTableView.swift
> +//
`Cannot find type 'ContentSizedTableView' in scope`
에러가 뜹니다. 다시 확인하여 PR 올려주세요

2024-03-04 11:28 UTC, yenny42 requested changes
**`Cannot find type 'ContentSizedTableView' in scope`**
에러가 뜹니다. 다시 확인하여 PR 올려주세요

2024-03-04 11:37 UTC, yenny42 requested changes
테이블뷰 관련해서 링크 하나 달았습니다
디자인 할 때는 해당 속성 상상하고 만든거라... 고려 부탁드릴게요

2024-03-04 11:37 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +    private func setupTableView() {
팀 코드 컨벤션 상, setTableView가 맞을 것 같습니다

2024-03-04 11:37 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +    }()
p1;
모서리가 둥그런 모양에 관련된 속성으로 .insetgrouped 라는게 있습니다
https://developer.apple.com/documentation/uikit/uitableview/style/insetgrouped
직접 프레임을 조정하는 것 보다는 이게 더 좋은 접근일 것 같아요!
현재는 프레임이 좀.. 깨지기도 하는 것 같아서요🤣 한 번 확인해보시고 긍정적으로 검토해주세요~

2024-03-04 12:27 UTC, codeIsGone reviewed
고생하셨습니다! 리뷰 남겼어요.

2024-03-04 12:27 UTC, codeIsGone commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
> +
p4;
forEach 사용해보시는 건 어떤가요?

2024-03-04 12:27 UTC, codeIsGone commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
> +
p3;
UI 관련 레이아웃 설정들을 메서드로 따로 구현해서 넣어보시는 건 어떤가요?

2024-03-04 12:27 UTC, codeIsGone commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
> +        label.font = UIFont.systemFont(ofSize: 16)
p1;
컬러와 폰트 모두 디자인 시스템 적용해주시면 좋을 것 같습니다!

2024-03-04 12:27 UTC, codeIsGone commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +
p1;
컬러와 폰트 모두 디자인 시스템 적용해주시면 좋을 것 같습니다!

2024-03-04 12:32 UTC, yenny42 requested changes

2024-03-04 12:32 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +extension GroupListView: UITableViewDelegate {
q;
셀 선택 시 스와이프가 나오도록 하기로 했던 것 같은데 제가 기억하는게 맞을까요?
맞다면 해당 부분도 구현해주세요!

2024-03-04 12:34 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
> +
override에는 직접 코드를 구현하지 않고 메서드로 사용하는 것을 권장한다고 합니다! 🥸

2024-03-04 17:21 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
> +
해결했습니다! [b7e6faf](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/b7e6faf51e97b0dcd53474aaf64f0e4bfa5197a1)

2024-03-04 17:27 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
> +}
작업완료했습니다. [61e48a3](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/61e48a32126e51d47aa20a14983e97ce41674aa0)

2024-03-04 17:31 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +        // 스와이프 편집 버튼 누르면 호출되는 메서드
작업완료하였습니다. [f48dc78](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/f48dc7807d297b9e3611b852857153905b98adac)

2024-03-04 17:46 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +final class GroupListView: UIView {
작업완료하였습니다. [c41c007](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/c41c007e1d045c93194d8b8d5c1d8817c1691ba2)

2024-03-04 18:08 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/TodoList/ViewController.swift
>  class ViewController: UIViewController {
작업완료하였습니다! [ea25fcf](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/ea25fcf671224123176aec0468784e83e7a0e194)

2024-03-04 18:13 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +}
코드작성하다가 따로따로 작성을 했었는데 그대로 커밋을 했네요 ㅠㅠ [a964930](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/a96493063ebfe780344121e4c8ecd8992f1dd69d)

2024-03-04 18:19 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +    private func setupTableView() {
수정했습니다 [e656e9a](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/e656e9a1e29f7a6857bc6630d0c5102d60ff7fc1)

2024-03-04 18:21 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/ContentSizedTableView.swift
> +}
확인했습니다!

2024-03-04 19:14 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
> +
작업완료하였습니다. [dafd66a](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/dafd66a09586f840e35f2b8c4a2a96bccc4c0d88)

2024-03-04 19:19 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
> +
레이아웃 관련 코드들을 메서드로 만들어서 작성 해두었습니다. [fb63eae](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/fb63eaefa853830e8cd075c55c38ddbf9be7e8f7)

2024-03-05 01:14 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListTableViewCell.swift
> +        label.font = UIFont.systemFont(ofSize: 16)
작업완료했습니다! [f526d87](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/f526d875369b811179bfbf84d19ae256abcea406)

2024-03-05 01:15 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +
작업완료했습니다! [f526d87](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/f526d875369b811179bfbf84d19ae256abcea406)

2024-03-05 01:32 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +extension GroupListView: UITableViewDelegate {
선택시 스와이프가 나오는 로직을 구현해보고있는데 생각보다 어렵네요ㅠ

2024-03-05 01:32 UTC, yenny42 requested changes

2024-03-05 01:32 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +    private func setupAddButton() {
p2;
코드 컨벤션에 따라 메서드명 변경해주세요!

2024-03-05 01:32 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +            make.width.equalTo(355)
p1;
너비값을 고정으로 두면 기기 사이즈 변경시 100퍼센트 깨질거라고 생각합니다!
leading, trailing을 활용하는 방안으로 변경해주세요 🙂

2024-03-05 01:32 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +        addButton.titleLabel?.font = UIFont.systemFont(ofSize: 16)
p1;
TDStyle.font를 사용해주세요

2024-03-05 01:32 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +//    }
사용하지 않는 주석은 삭제해주세요!

2024-03-05 01:32 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +                       to destinationIndexPath: IndexPath) {
Vertical Parameter Alignment Violation: Function parameters should be aligned vertically if they're in multiple lines in a declaration (vertical_parameter_alignment)

린트 이슈 뜹니다!

2024-03-05 01:34 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +    private func setupAddButton() {
완료하였습니다 [c5488ea](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/c5488eab499e5da4712040ba490348a1b31e6948)

2024-03-05 01:38 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +            make.width.equalTo(355)
완료하였습니다. [e3cbde4](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/e3cbde472bf106272901c3c33dc2a6c49a6c093b)

2024-03-05 01:41 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +            make.top.equalToSuperview().offset(155)
확인해보고 사용해보겠습니다. 감사합니다! [a28f7b2](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/a28f7b2be361dac5172cb856a8a568cce488e955)

2024-03-05 01:44 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +            make.height.equalTo(40)
수정하였습니다 [57b19a9](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/57b19a9196c3e40465c6e984f155aa68a858f459)

2024-03-05 01:45 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +        addButton.titleLabel?.font = UIFont.systemFont(ofSize: 16)
작업완료했습니다. [aecc580](https://github.com/NBCAMP-ToDwoong/todwoong/pull/32/commits/aecc5807b7a4b62c258a3cc9f5a1e6fdc6ec5644)

2024-03-05 01:52 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +    }
네 린트이슈입니다! 현재는 이분도 수정해보았는데 바로 고치기가 어려울거같아서 후순위로 작업하겠습니다...ㅠㅠ

2024-03-05 01:53 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +//    }
삭제 하였습니다.

2024-03-05 01:54 UTC, Whited123 commented on ToDwoong/ToDwoong/Presentation/GroupList/View/GroupListView.swift
> +                       to destinationIndexPath: IndexPath) {
확인완료했습니다!

2024-03-05 02:01 UTC, yenny42 approved these changes
진짜 수고많으셨습니다! 🥹

2024-03-05 02:04 UTC, codeIsGone approved these changes
고생하셨습니다!

2024-03-05 03:33 UTC, closed without merging