[Feat] #17 - 투두 추가화면 UI 구현
NBCAMP-ToDwoong/todwoong pull request #35
Opened 2024-03-04 13:17 UTC by mirae0312

## 연관된 이슈
#17, #29

> 

## 작업 내용

 제목 : 텍스트필드 적용
 날짜 : 탭 > 셀 아래에 데이트피커 반응형 구현
 시간 : 탭 > 셀 아래에 타임피커 반응형 구현
 위치 : MapKit 사용 지도화면, 지도에서 중앙핀 기준으로 좌표값 리턴 구현
 그룹 : 구현 예정 
>

## 리뷰 요구사항

코드 컨벤션 지키려고 노력했으나 놓친 부분 있다면 작성해주세요
FIXME 부분은 아직 테스트중입니다
추후 UI리펙토링 예정입니다. (상세내용 #29 참고)
>

## 스크린샷
|제목|
|---|
|<img src="https://github.com/NBCAMP-ToDwoong/todwoong/assets/77021071/0175a04d-b612-49fe-bc9a-affba9620e58" width="300"/>|

2024-03-04 13:17 UTC, yenny42 commented on ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AddTodoMapPin.imageset/free-icon-pin-2948253 1.png
파일 이름도 변경해주시면 좋을 것 같아요!

2024-03-04 13:19 UTC, mirae0312 commented on ToDwoong/ToDwoong/Global/Support/Assets.xcassets/AddTodoMapPin.imageset/free-icon-pin-2948253 1.png
변경 완료했습니다 🥰

2024-03-04 13:20 UTC, yenny42 requested changes

2024-03-04 13:32 UTC, yenny42 requested changes

2024-03-04 13:32 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/AddTodo/View/AddTodoLocationPickerView.swift
> +class AddTodoLocationPickerView: UIView {
q;
날짜, 시간 세팅하고 날짜를 변경하려고 하면 날짜가 사라집니다!
이미 설정된 시간이 있다면 날짜를 수정하더라도 시간이 사라지면 안될거 같아요ㅠㅠ

![Mar-04-2024 22-28-46](https://github.com/NBCAMP-ToDwoong/todwoong/assets/107637741/d0e0edaf-7213-40d4-8eb1-9a610c9e0a9d)

2024-03-04 13:33 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DatePickerCollectionViewCell.swift
> +}
프로토콜을 같이 쓰는걸 선호하는편이지만 참고하겠습니다~ 감사합니다 😊

2024-03-04 13:34 UTC, yenny42 requested changes

2024-03-04 13:34 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DatePickerCollectionViewCell.swift
> +class DatePickerCollectionViewCell: UICollectionViewCell {
p3;
(코드 전체)
상속하지 않을 클래스는 final 키워드를 사용함으로써 최적화 등에 도움을 줄 수 있다고 알고 있어요~
저희 다같이 class 앞에 final 키워드를 챙겨서 작성해봅시다!!

2024-03-04 13:43 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DatePickerCollectionViewCell.swift
> +class DatePickerCollectionViewCell: UICollectionViewCell {
7afc55d final 키워드 추가했습니다 😊

2024-03-04 13:52 UTC, yenny42 requested changes

2024-03-04 13:52 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoLocationPickerViewController.swift
> +import MapKit
p3
MapKit은 퍼스트파티로 알고있습니다!

2024-03-04 13:52 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/AddTodo/View/AddTodoLocationPickerView.swift
> +        label.font = UIFont.systemFont(ofSize: 16)
p3;
TDStyle.font 를 사용해주세요! 😋

2024-03-04 13:52 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimeOptionCell.swift
> +        label.font = UIFont.systemFont(ofSize: 16)
p3;
TDStyle.font 를 사용해주세요! 😋

2024-03-04 13:52 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Cells/InfoCollectionViewCell.swift
> +        addSubview(symbolImageView)
p5;
반복작업은 forEach를 사용해서 간결하게 만들어볼 수 있을 것 같습니다 :D
개인적으로 간결하고 유지보수하기 쉬워서 이렇게 사용하는걸 좋아합니다

2024-03-04 13:52 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Cells/InfoCollectionViewCell.swift
> +
p3;
(전체코드)
설정 메서드는 extension에 적어주시면 좋을 것 같아요
가독성이 좋아지고 기능 분리적인 측면에서 명확해진다고 생각합니다🥸

2024-03-04 13:52 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/AddTodo/View/AddTodoLocationPickerView.swift
> +import MapKit
p3
MapKit은 퍼스트파티로 알고있습니다!

2024-03-04 13:52 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimeOptionCell.swift
> +
코드 기능별로 확장에 분리해주시면 좋을 것 같아요!

2024-03-04 13:58 UTC, yenny42 commented
디자인할 때 기본 간격을 16정도로 잡았었는데 현재 날짜, 시간 Leading 간격이 16보다 작은듯 합니다!
한 번 확인 부탁드릴게요ㅎㅎ

2024-03-04 14:00 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimePickerContainerCell.swift
> +        cell.titleLabel.text = indexPath.item == 0 ? "날짜" : "시간"
디자인할 때 기본 간격을 16정도로 잡았었는데 현재 날짜, 시간 같은 셀 타이틀의 Leading 간격이 16보다 작은듯 합니다!
한 번 확인 부탁드릴게요ㅎㅎ
(이것도 https://github.com/NBCAMP-ToDwoong/todwoong/issues/29 에서 하시는 걸까여?)

2024-03-04 16:20 UTC, codeIsGone approved these changes
고생하셨습니다!

2024-03-04 21:40 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/AddTodo/View/AddTodoLocationPickerView.swift
> +class AddTodoLocationPickerView: UIView {
f257634 수정완료 👏

2024-03-04 21:44 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoLocationPickerViewController.swift
> +import MapKit
f257634 수정완료 👏

2024-03-04 22:33 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimeOptionCell.swift
> +
cea6d0d 적용완료 😊

2024-03-04 22:33 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Cells/InfoCollectionViewCell.swift
> +
cea6d0d 적용완료 😊

2024-03-04 22:33 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Cells/InfoCollectionViewCell.swift
> +        addSubview(symbolImageView)
cea6d0d 적용완료 😊

2024-03-04 22:34 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Cells/InfoCollectionViewCell.swift
> +        addSubview(symbolImageView)
`private func setUI() {
        [mapView, centerPinImageView, searchBar].forEach { addSubview($0) }
        setAddressContainerView()
    }`
    요런식으로 사용했습니다 🤔

2024-03-04 22:35 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DateTimeOptionCell.swift
> +        label.font = UIFont.systemFont(ofSize: 16)
cea6d0d 적용완료 😊

2024-03-04 22:35 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/AddTodo/View/AddTodoLocationPickerView.swift
> +        label.font = UIFont.systemFont(ofSize: 16)
cea6d0d 적용완료 😊

2024-03-04 22:46 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Cells/DatePickerCollectionViewCell.swift
> +}
de1a177 프로토콜 폴더 분리했습니다

2024-03-05 01:05 UTC, yenny42 approved these changes
수고하셨습니다 😁

2024-03-05 01:12 UTC, merged