[Feat] #38 - 캘린더 UI 구현
NBCAMP-ToDwoong/todwoong pull request #48
Opened 2024-03-05 11:46 UTC by mirae0312

## 연관된 이슈

#38 
> 

## 작업 내용

SFCalandar사용해서 캘린더 구현
캘린더 페이지. 캘린더 UI 구현.
>

## 리뷰 요구사항

SFCalandar사용.
테마색 적용완료.
테마폰트 적용완료.
한글 적용 완료.
event dot 설정 완료.

>

## 스크린샷 
|구현화면|
|---|
|<img src="https://github.com/NBCAMP-ToDwoong/todwoong/assets/77021071/14e20b56-6b45-4894-9d2c-5063406f20b5" width="300"/>|

-->

2024-03-05 12:00 UTC, Whited123 approved these changes
고생하셨습니다.

2024-03-05 12:45 UTC, codeIsGone commented on ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift
> +
p5;
개행 삭제하시는 거 어떨까요?

2024-03-05 12:46 UTC, codeIsGone commented on ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift
> +
p2;
컨벤션에 따라 Life Cycle 마크 주석 추가해주시는 거 어떨까요?

2024-03-05 12:48 UTC, codeIsGone commented on ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift~HEAD
> +class AddTodoGroupSelectController: UIViewController {
p3;
final 키워드 추가하시는 건 어떨까요?

2024-03-05 12:50 UTC, codeIsGone commented on ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift~HEAD
> +    let tableView = UITableView()
p2;
접근범위를 고려하여 코드 전반에 접근제어자를 추가해주면 어떨까요?

2024-03-05 14:12 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift
> +
3579791 수정완료

2024-03-05 14:13 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift
> +
3579791 수정완료

2024-03-05 14:13 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/AddTodo/ViewController/AddTodoGroupSelectController.swift~HEAD
> +class AddTodoGroupSelectController: UIViewController {
3579791 수정완료

2024-03-05 14:28 UTC, codeIsGone approved these changes
수고하셨습니다!

2024-03-06 00:42 UTC, yenny42 requested changes

2024-03-06 00:42 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/AddTodo/Protocols/AddTodoGroupSelectControllerDelegate.swift
> +//
오 프로토콜.. AddTodo의 프로토콜이면 AddTodoProtocols 해서 묶어서 쓰자는 의미였는데 싹 분리를 해주셨네요 🤣 어느면에서는 이것도 좋은 것 같아요

2024-03-06 00:42 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoViewController.swift
>      private func convertTodoData(_ todo: Todo) -> TodoModel {
자꾸 에러가 나네요... 일단 이걸로 변경해주세요ㅠ
```
    private func convertTodoData(_ todo: Todo) -> TodoModel {
        var convertedCategory: CategoryModel?
        var convertedTodo: TodoModel

        if let category = todo.category {
            convertedCategory = CategoryModel(id: category.id,
                                              title: category.title!,
                                              color: category.color,
                                              indexNumber: category.indexNumber,
                                              todo: nil) // 일단 nil로 초기화
        }

        convertedTodo = TodoModel(id: todo.id, title: todo.title!,
                                  dueDate: todo.dueDate, dueTime: todo.dueTime,
                                  place: todo.place,
                                  isCompleted: todo.isCompleted, fixed: todo.fixed,
                                  timeAlarm: todo.timeAlarm, placeAlarm: todo.placeAlarm,
                                  category: convertedCategory)

        convertedCategory?.todo = convertedTodo

        return convertedTodo
    }
```

2024-03-06 00:42 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/Calander/ViewController/TodoCalandarController.swift
> +final class TodoCalendarController: UIViewController, FSCalendarDelegate, FSCalendarDataSource {
개인적인 생각인데 오늘 날짜에 고정으로 select 모양 들어가있는거 좀 헷갈리네요!
오늘 날짜라면 모를까 유저가 다른 날짜를 누른다면 저 디자인이 빠졌으면 좋겠어요

2024-03-06 00:59 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/Calander/ViewController/TodoCalandarController.swift
> +final class TodoCalendarController: UIViewController, FSCalendarDelegate, FSCalendarDataSource {
그렇게 수정한다면 오늘날짜를 표시해주는 부분이 없는데 🤔
그럼 지금 선택 컬러를 오늘 날짜 select 모양을 주고
선택을 테마컬러로 하는건어떨까요?

![스크린샷 2024-03-06 오전 9 59 29](https://github.com/NBCAMP-ToDwoong/todwoong/assets/77021071/8b5e0a9d-386b-4c08-921e-257c0d42b50e)

2024-03-06 01:40 UTC, yenny42 commented on ToDwoong/ToDwoong/Presentation/Calander/ViewController/TodoCalandarController.swift
> +final class TodoCalendarController: UIViewController, FSCalendarDelegate, FSCalendarDataSource {
클래스 이름 그냥 CalandarViewController로 하셔도 될 것 같습니다 :D

2024-03-06 02:12 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/Calander/ViewController/TodoCalandarController.swift
> +final class TodoCalendarController: UIViewController, FSCalendarDelegate, FSCalendarDataSource {
다음피쳐에 반영하겠습니다!

2024-03-06 02:12 UTC, Whited123 approved these changes
고생하셨습니다

2024-03-06 02:22 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/TodoList/ViewController/TodoViewController.swift
>      private func convertTodoData(_ todo: Todo) -> TodoModel {
d84a161 수정완료 😊

2024-03-06 02:23 UTC, mirae0312 commented on ToDwoong/ToDwoong/Presentation/Calander/ViewController/TodoCalandarController.swift
> +final class TodoCalendarController: UIViewController, FSCalendarDelegate, FSCalendarDataSource {
다음 피쳐에 같이 수정해서 올리겠습니다 🥲

2024-03-06 02:51 UTC, yenny42 approved these changes
수고하셨습니다~

2024-03-06 05:51 UTC, merged