[Feat]#83-캘린더 UI수정
NBCAMP-ToDwoong/todwoong pull request #90
Opened 2024-03-09 10:58 UTC by mirae0312

## 연관된 이슈

#83
> 

## 작업 내용

>테이블뷰 UI 변경
 ㄴ 테이블뷰 배경색 라이트그레이로 변경
 ㄴ  테이블뷰 배경 둥글기 20으로 변경
 ㄴ 지정 폰트사용
 ㄴ 투두없을때 이미지 'dwoong'으로 변경
중복 커스텀 네이게이션바 제거

## 리뷰 요구사항 (선택)

>

## 스크린샷 (선택)
|수정화면|
|---|
|<img src="https://github.com/NBCAMP-ToDwoong/todwoong/assets/77021071/09761904-c9af-48be-8787-df14567ae7a7" width="300"/>|

![simulator_screenshot_29C58C8F-F879-4BB2-B652-9A1CE1812505]()

2024-03-09 11:19 UTC, yenny42 commented
리스트 비어있는 화면 디자인 희곤님과 통일해주세요!

2024-03-09 12:57 UTC, yenny42 requested changes
p3;
리스트가 비어있을 때 보이는 화면 디자인 희곤님과 통일해주세요!

2024-03-10 06:41 UTC, Whited123 approved these changes
확인했습니다!

2024-03-10 06:46 UTC, yenny42 approved these changes

2024-03-10 06:46 UTC, merged